---
  - hosts: all
    remote_user: ubuntu
    become: true
    gather_facts: no
    ignore_errors: true
    tasks: 
      - name: Perform apt update
        shell: apt update
      - name: Install apache2 package
        apt:
          name: apache2 
          state: present
      - name: Copy file with owner & permissions
        copy:
          src: mywebsite.html
          dest: /var/www/html/
          owner: ubuntu
          group: root
          mode: '0777'
      - name: Copy jar file to target machine
        copy:
          src: target/
          dest: /tmp/
          owner: ubuntu
          group: root
          mode: '0700'
      - name: Start apache2 service
        service: 
          name: apache2
          state: started
